In [1]:
import pandas as pd

import sqlalchemy as db # Gestionar y conectar con bases de datos

from sqlalchemy import text # Funcion text, construir consultas SQL de manera segura

In [2]:
# Creare la conexion al motor de BD
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")
# establesco la conexion
conn = engine.connect()

# Cargamos datos a la dimension Movie

In [ ]:
query = """
    SELECT 
        movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
        gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant
    FROM movie 
    INNER JOIN participant 
    ON movie.movieID=participant.movieID
    INNER JOIN person
    ON person.personID = participant.personID
    INNER JOIN movie_gender 
    ON movie.movieID = movie_gender.movieID
    INNER JOIN gender 
    ON movie_gender.genderID = gender.genderID
"""

In [7]:
movies_data = pd.read_sql(query, con=engine)

movies_data['movieID'] = movies_data['movieID'].astype('int')

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [13]:
# Cargar premios de Peliculas
movies_awards = pd.read_csv('data/Awards_movie.csv')

# Convertir el id a int
movies_awards['movieID'] = movies_awards['movieID'].astype('int')

#renonbrar el campo
movies_awards.rename(columns={"Aware":"Award"}, inplace=True)

movies_awards

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [ ]:
# Cruzar la informacion de movies + moview award
movie_data = pd.merge(movies_data, movies_awards, left_on='movieID', right_on='movieID')

movie_data

,movieID,title,releaseDate,gender,participantName,roleparticipant,IdAward,Award
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [16]:
# Creare la conexion al motor de BD
engine_dw = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")
# establesco la conexion
conn_dw = engine_dw.connect()

In [18]:
movie_data = movie_data.rename(columns={'releaseDate': 'releaseMovie', 'Award': 'awardMovie'})
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,IdAward,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [19]:
movie_data = movie_data.drop(columns=['IdAward'])
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [20]:
# Cargar a la BD dw_netflix
movie_data.to_sql('dimMovie', con=conn_dw, if_exists='append', index=False)

3