In [1]:
import pandas as pd

import sqlalchemy as db # Gestionar y conectar con bases de datos

from sqlalchemy import text # Funcion text, construir consultas SQL de manera segura

In [2]:
# Creare la conexion al motor de BD
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")
# establesco la conexion
conn = engine.connect()

# Cargamos datos a la dimension Movie

In [ ]:
query = """
    SELECT 
        movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
        gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant
    FROM movie 
    INNER JOIN participant 
    ON movie.movieID=participant.movieID
    INNER JOIN person
    ON person.personID = participant.personID
    INNER JOIN movie_gender 
    ON movie.movieID = movie_gender.movieID
    INNER JOIN gender 
    ON movie_gender.genderID = gender.genderID
"""

In [7]:
movies_data = pd.read_sql(query, con=engine)

movies_data['movieID'] = movies_data['movieID'].astype('int')

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [13]:
# Cargar premios de Peliculas
movies_awards = pd.read_csv('data/Awards_movie.csv')

# Convertir el id a int
movies_awards['movieID'] = movies_awards['movieID'].astype('int')

#renonbrar el campo
movies_awards.rename(columns={"Aware":"Award"}, inplace=True)

movies_awards

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [ ]:
# Cruzar la informacion de movies + moview award
movie_data = pd.merge(movies_data, movies_awards, left_on='movieID', right_on='movieID')

movie_data

,movieID,title,releaseDate,gender,participantName,roleparticipant,IdAward,Award
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [ ]:
# Creare la conexion al motor de BD
engine_dw = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")

# establesco la conexion
conn_dw = engine_dw.connect()

In [18]:
movie_data = movie_data.rename(columns={'releaseDate': 'releaseMovie', 'Award': 'awardMovie'})
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,IdAward,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [19]:
movie_data = movie_data.drop(columns=['IdAward'])
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [20]:
# Cargar a la BD dw_netflix
movie_data.to_sql('dimMovie', con=conn_dw, if_exists='append', index=False)

3

# Cargamos datos a la dimension USER

In [22]:
# leer la tabla usuario
users = pd.read_csv("data/users.csv", sep="|")

users.head()

    idUser     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [ ]:
users = users.rename(columns={'idUser':'userID'})

users.head()

    userID     username    country subscription
0  1002331      user123        USA      Premium
1  1002332  gamerGirl97     Canada        Basic
2  1002333   techMaster         UK      Premium
3  1002334    soccerFan     Brazil        Basic
4  1002335    travelBug  Australia      Premium

In [26]:
# Cargar la informacion
users.to_sql('dimUser', con=conn_dw, if_exists='append', index=False)

20

# Cargar la tabla de echos

In [28]:
# Lista de usuarios
users_id = users['userID']

# Lista de peliculas
movies_id = movie_data['movieID']

In [30]:
movies_id

0    80192187
1    80210920
2    81157374
Name: movieID, dtype: int64

In [29]:
users_id.head()

0    1002331
1    1002332
2    1002333
3    1002334
4    1002335
Name: userID, dtype: int64

In [33]:
watchs_data = pd.merge(users_id, movies_id, how='cross')

watchs_data.head(9)

    userID   movieID
0  1002331  80192187
1  1002331  80210920
2  1002331  81157374
3  1002332  80192187
4  1002332  80210920
5  1002332  81157374
6  1002333  80192187
7  1002333  80210920
8  1002333  81157374

In [34]:
import random
from datetime import datetime, timedelta

def gen_rating():
    # Generar un número aleatorio entre 0 y 5 con 1 solo decimal
    numero_aleatorio = round(random.uniform(0, 5), 1)
    # Mostrar el número aleatorio
    return numero_aleatorio

def gen_timestamp():
    # Generar un timestamp aleatorio dentro de un rango específico
    start_date = datetime(2024, 1, 15)
    end_date = datetime(2024, 4, 6)

    # Calcular un valor aleatorio entre start_date y end_date
    random_date = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

    # Mostrar el timestamp aleatorio
    return random_date

In [59]:
watchs_data["rating"] = watchs_data['movieID'].apply(lambda x: gen_rating())

watchs_data["timestamp"] = watchs_data['movieID'].apply(lambda x: gen_timestamp())

In [61]:
watchs_data.head(9)

    userID   movieID  rating           timestamp
0  1002331  80192187     3.1 2024-02-24 15:18:33
1  1002331  80210920     4.1 2024-01-25 07:16:03
2  1002331  81157374     0.1 2024-01-19 06:02:32
3  1002332  80192187     3.8 2024-03-02 04:39:06
4  1002332  80210920     0.4 2024-01-22 11:22:24
5  1002332  81157374     3.3 2024-01-16 08:52:20
6  1002333  80192187     3.8 2024-01-26 01:22:22
7  1002333  80210920     0.5 2024-03-29 05:44:29
8  1002333  81157374     2.7 2024-03-24 08:09:54